export const priceKeywords = ["harga", "price", "idr", "rp"];
export const driverKeywords = ["driver", "drivers"];
export const woodKeywords = [
  "wood",
  "fairway wood",
  "fairway woods",
  "fairwaywoods",
  "fairwaywood",
];
export const hybridKeywords = ["rescue", "hybrid"];
export const ironsKeywords = [
  "irons",
  "iron",
  "ironset",
  "iron set",
  "ironsets",
  "iron sets",
];
export const clubModels = {
  Taylormade: [
    "Qi10",
    "Qi10 Max",
    "Stealth 2",
    "Stealth",
    "SIM 2",
    "SIM 2 Max",
    "SIM",
    "SIM Max",
    "P790 (2023)",
    "P790 (2021)",
    "SIM Max OS",
  ],
  Titleist: [
    "GT2",
    "GT3",
    "TSR1",
    "TSR2",
    "TSR3",
    "T100",
    "T150",
    "T200",
    "T350",
    "T100S",
    "T300",
    "TS1",
    "TS2",
    "TS3",
    "TSi1",
    "TSi2",
    "TSi3",
  ],
  PING: [
    "G425",
    "G430 Max",
    "G430 Max 10K",
    "i530",
    "G730",
    "G430",
    "i230",
    "i525",
    "i59",
  ],
  Callaway: [
    "Paradym Ai Smoke Max",
    "Paradym Ai Smoke Max D",
    "Paradym Ai Smoke Max Fast",
    "Paradym",
    "Paradym X",
    "Rogue ST MAX",
    "Rogue ST MAX D",
    "Epic Speed",
    "Epic MAX",
    "Mavrik",
    "Mavrik 22",
    "Mavrik Max",
    "Apex 21",
    "Apex Pro 21",
    "X-Forged CB",
  ],
  Mizuno: [
    "Pro 241",
    "Pro 243",
    "Pro 245",
    "JPX923 Hot Metal",
    "JPX923 Hot Metal Pro",
    "JPX923 Forged",
    "JPX923 Tour",
    "Pro 221",
    "Pro 223",
    "Pro 225",
    "JPX921 Hot Metal",
    "JPX921 Hot Metal Pro",
    "JPX921 Forged",
    "JPX921 Tour",
  ],
  Cobra: [
    "Darkspeed X",
    "Darkspeed Max",
    "AeroJet",
    "AeroJet Max",
    "LTDx",
    "LTDx Max",
    "Radspeed",
    "Radspeed XB",
    "Radspeed XD",
    "King Forged Tec",
    "King Forged Tec One Length",
    "King Forged Tec Copper",
  ],
};
export const usedKeywords = ["used", "bekas", "mint", "like new", "likenew"];
export const newKeywords = [
  "new",
  "brandnew",
  "brand new",
  "baru",
  "BNIB",
  "BNIP",
];
export const soldKeywords = [
  "sold",
  "laku",
  "purchased",
  "sold out",
  "soldout",
];
