const productKeywords = [
  "Taylormade Qi10 Ironset",
  "Taylormade P790 Ironset",
  "Taylormade Stealth Ironset",
  "Taylormade SIM 2 Max Ironset",
  "Taylormade SIM 2 Max OS Ironset",
  "Taylormade SIM Max Ironset",
  "Taylormade SIM Max OS Ironset",
  "Taylormade Qi10 Driver",
  "Taylormade Qi10 Max Driver",
  "Taylormade Stealth 2 Driver",
  "Taylormade Stealth Driver",
  "Taylormade SIM 2 Driver",
  "Taylormade SIM 2 Max Driver",
  "Taylormade SIM Driver",
  "Taylormade SIM Max Driver",
  "Taylormade SIM Max Wood 3",
  "Taylormade SIM Max Wood 5",
  "Taylormade Qi10 Max Wood 3",
  "Taylormade Qi10 Max Wood 5",
  "Taylormade Stealth 2 Wood 3",
  "Taylormade Stealth 2 Wood 5",
  "Taylormade Stealth Wood 3",
  "Taylormade Stealth Wood 5",
  "Taylormade SIM Max Hybrid 2",
  "Taylormade SIM Max Hybrid 3",
  "Taylormade SIM Max Hybrid 4",
  "Taylormade SIM Max Hybrid 5",
  "Taylormade Qi10 Max Hybrid 2",
  "Taylormade Qi10 Max Hybrid 3",
  "Taylormade Qi10 Max Hybrid 4",
  "Taylormade Qi10 Max Hybrid 5",
  "Taylormade Stealth 2 Hybrid 2",
  "Taylormade Stealth 2 Hybrid 3",
  "Taylormade Stealth 2 Hybrid 4",
  "Taylormade Stealth 2 Hybrid 5",
  "Taylormade Stealth Hybrid 2",
  "Taylormade Stealth Hybrid 3",
  "Taylormade Stealth Hybrid 4",
  "Taylormade Stealth Hybrid 5",
  "Titleist T350 Ironset",
  "Titleist T100 Ironset",
  "Titleist T100S Ironset",
  "Titleist T300 Ironset",
  "Titleist TSR2 Driver",
  "Titleist TSR3 Driver",
  "Titleist TSi1 Driver",
  "Titleist TSi2 Driver",
  "Titleist TSi3 Driver",
  "Titleist TSR1 Wood 3",
  "Titleist TSR1 Wood 5",
  "Titleist TSR2 Wood 3",
  "Titleist TSR2 Wood 5",
  "Titleist TSR3 Wood 3",
  "Titleist TSR3 Wood 5",
  "Titleist TSi1 Wood 3",
  "Titleist TSi1 Wood 5",
  "Titleist TSi2 Wood 3",
  "Titleist TSi2 Wood 5",
  "Titleist TSi3 Wood 3",
  "Titleist TSi3 Wood 5",
  "PING i530 Ironset",
  "PING G730 Ironset",
  "PING G430 Ironset",
  "PING i230 Ironset",
  "PING i525 Ironset",
  "PING i59 Ironset",
  "PING G425 Ironset",
  "PING G425 Max Driver",
  "PING G430 Max Driver",
  "PING G430 Max 10K Driver",
  "PING G430 Wood 3",
  "PING G430 Wood 5",
  "PING G425 Wood 3",
  "PING G425 Wood 5",
  "Callaway Paradym Ai Smoke Ironset",
  "Callaway Paradym Ai Smoke Max Fast Ironset",
  "Callaway Paradym Ironset",
  "Callaway Paradym X Ironset",
  "Callaway Rogue ST Max Ironset",
  "Callaway Rogue ST Max OS Ironset",
  "Callaway Apex 21 Ironset",
  "Callaway Apex Pro 21 Ironset",
  "Callaway X-Forged CB Ironset",
  "Callaway Mavrik Ironset",
  "Callaway Mavrik Max Ironset",
  "Callaway Paradym Ai Smoke Max Driver",
  "Callaway Paradym Ai Smoke Max D Driver",
  "Callaway Paradym Ai Smoke Max Fast Driver",
  "Callaway Paradym Driver",
  "Callaway Paradym X Driver",
  "Callaway Rogue ST MAX Driver",
  "Callaway Rogue ST MAX D Driver",
  "Callaway Epic Speed Driver",
  "Callaway Epic MAX Driver",
  "Callaway Mavrik Driver",
  "Callaway Mavrik 22 Driver",
  "Callaway Mavrik Max Driver",
  "Callaway Paradym Ai Smoke MAX Wood 3",
  "Callaway Paradym Ai Smoke MAX Wood 5",
  "Callaway Paradym Wood 3",
  "Callaway Paradym Wood 5",
  "Callaway Mavrik Wood 3",
  "Callaway Mavrik Wood 5",
  "Callaway Rogue ST MAX Wood 3",
  "Callaway Rogue ST MAX Wood 5",
  "Mizuno Pro 241 Ironset",
  "Mizuno Pro 243 Ironset",
  "Mizuno Pro 245 Ironset",
  "Mizuno JPX923 Hot Metal Ironset",
  "Mizuno JPX923 Hot Metal Pro Ironset",
];

export default productKeywords;
